.globalzp nmi_switch
.globalzp work
.globalzp ppumask_shadow
.globalzp cursor_x
.globalzp cursor_y
.globalzp cursor_ani_timer
.globalzp cursor_row
.globalzp cursor_col
.globalzp board_squares
.globalzp turn
.globalzp last_square
.globalzp new_game_ctrl
.globalzp game_state
.globalzp ppu_upload_buf
.globalzp ppu_upload_buf_ptr
.globalzp p1_score
.globalzp p1_score_digits
.globalzp p2_score
.globalzp p2_score_digits
.globalzp joy_pressed
.globalzp joy_held
.globalzp sq1_sfx_queue
.globalzp sq2_sfx_timer
.globalzp sq2_sfx_queue
.globalzp sq2_sfx_buf
.global   spr_cursor_1
.global   spr_cursor_2
.global   spr_cursor_3
.global   spr_cursor_4
.global   spr_p1_score_digit_1
.global   spr_p1_score_digit_2
.global   spr_p2_score_digit_1
.global   spr_p2_score_digit_2
